# Local Kubernetes Cluster with Terraform + Ansible

Provisions a 3-node Kubernetes cluster on KVM/libvirt VMs using Terraform for infrastructure and Ansible for cluster configuration. Designed for WSL2 on Windows with nested virtualization.

## Architecture

- **k8s-control-plane** — 4GB RAM, 2 vCPU, 20GB disk (192.168.122.10)
- **k8s-worker-1** — 2GB RAM, 2 vCPU, 20GB disk (192.168.122.11)
- **k8s-worker-2** — 2GB RAM, 2 vCPU, 20GB disk (192.168.122.12)

All VMs run Ubuntu 24.04 (Noble Numbat) cloud image on a libvirt NAT network (`192.168.122.0/24`).

## Prerequisites

### WSL2 Configuration

Nested virtualization must be enabled. In `%USERPROFILE%\.wslconfig`:

```ini
[wsl2]
nestedVirtualization=true
```

In `/etc/wsl.conf`:

```ini
[boot]
systemd=true

[user]
default=<your-username>

[network]
generateResolvConf = false
```

DNS must be manually configured in `/etc/resolv.conf`:

```
nameserver 8.8.8.8
nameserver 8.8.4.4
```

### Packages

```bash
sudo apt update && sudo apt install -y \
  qemu-kvm libvirt-daemon-system libvirt-clients \
  bridge-utils virtinst mkisofs xsltproc

sudo usermod -aG libvirt $(whoami)
sudo usermod -aG kvm $(whoami)
newgrp libvirt
```

### Terraform

```bash
wget https://releases.hashicorp.com/terraform/1.15.6/terraform_1.15.6_linux_amd64.zip
unzip terraform_1.15.6_linux_amd64.zip
sudo mv terraform /usr/local/bin/
```

### Ansible (in virtual environment)

```bash
python3 -m venv venv
source venv/bin/activate
pip install ansible
```

### SSH Key

```bash
ssh-keygen -t rsa -b 4096
```

The public key at `~/.ssh/id_rsa.pub` is automatically injected into VMs via cloud-init.

## Project Structure

```
iac/
├── terraform/
│   ├── providers.tf          # libvirt + null providers
│   ├── variables.tf          # Node definitions (IPs, resources)
│   ├── main.tf               # Pool, volumes, cloud-init, domains
│   ├── outputs.tf            # Generates Ansible inventory
│   └── templates/
│       ├── user_data.yml.tpl      # Cloud-init user config
│       ├── network_config.yml.tpl # Cloud-init network config
│       └── inventory.ini.tpl      # Ansible inventory template
├── ansible/
│   ├── inventory.ini         # Auto-generated by Terraform
│   └── k8s-setup.yml         # K8s cluster playbook
├── venv/                     # Python venv for Ansible
└── README.md
```

## Usage

### Deploy

```bash
cd terraform
terraform init
terraform plan
terraform apply
```

VMs take ~60 seconds after `terraform apply` for cloud-init to complete and SSH to become available.

### Verify

```bash
ssh kube@192.168.122.10
ssh kube@192.168.122.11
ssh kube@192.168.122.12
```

### Destroy

```bash
terraform destroy -auto-approve
```

### Full Rebuild

```bash
terraform destroy -auto-approve && terraform apply
```

## How It Works

**Terraform** creates the infrastructure: a libvirt storage pool, downloads the Ubuntu 24.04 cloud image, creates thin-clone disks for each node, builds cloud-init ISOs with user/network configuration, and defines KVM domains (VMs).

**Cloud-init** runs on first boot inside each VM: sets the hostname, creates the `kube` user with SSH key access, configures static IPs, disables swap, and loads kernel modules required by Kubernetes.

**Ansible** inventory is auto-generated by Terraform from the same node definitions in `variables.tf`, ensuring IPs are defined in one place.

## Known Issues (WSL2-Specific)

- **DNS in VMs**: libvirt's default NAT DNS forwarding may not work in WSL2. VMs use `8.8.8.8` / `8.8.4.4` directly instead of `192.168.122.1`.
- **Package updates in cloud-init**: `package_update: true` can hang cloud-init indefinitely if internet access from VMs is unreliable. Package installation is handled by Ansible instead.
- **Serial console**: `virsh console` requires kernel boot parameters (`console=ttyS0`) which aren't set by default on the cloud image. Use SSH for access.
- **libguestfs**: `virt-cat` / `guestmount` tools fail in WSL2 due to supermin issues. Use `qemu-nbd` to mount VM disks for debugging.

## Customization

Node count, IPs, memory, CPU, and disk size are configured in `variables.tf`:

```hcl
variable "nodes" {
  default = {
    "k8s-control-plane" = { ip = "192.168.122.10", memory = 4096, vcpu = 2, disk_gb = 20 }
    "k8s-worker-1"      = { ip = "192.168.122.11", memory = 2048, vcpu = 2, disk_gb = 20 }
    "k8s-worker-2"      = { ip = "192.168.122.12", memory = 2048, vcpu = 2, disk_gb = 20 }
  }
}
```

## .gitignore

Add to `.gitignore`:

```
venv/
terraform/.terraform/
terraform/.terraform.lock.hcl
terraform/terraform.tfstate
terraform/terraform.tfstate.backup
ansible/inventory.ini
*.iso
```
